### ISSUE TITLE
Downloaded collection gives error when expanded

### ISSUE THREAD

**Issue by iamjli** [fraenkel-lab/galaxy-neurolincs#4]
I'm not sure if this is a Galaxy issue or something on my end. 

Trying to download from `Protocol Selection (diMN18) - ATAC Pipeline` collection 156: `bamCoverage on collection 131`. I get this error when I double-click expand: 

![image](https://user-images.githubusercontent.com/7219365/43495124-4faae5e2-9504-11e8-9d14-c7506f5e107d.png)

And this error when I go through command line: 

```
> tar -xvzf 156_\ bamCoverage\ on\ collection\ 131.tgz
x bamCoverage on collection 131/iALS0BUU_diMN18_rep1.bigwig
x bamCoverage on collection 131/iALS0LPK_diMN18_rep1.bigwig
x bamCoverage on collection 131/iALS6ZLD_diMN18_rep1.bigwig
x bamCoverage on collection 131/iALS7VCZ_diMN18_rep1.bigwig
x bamCoverage on collection 131/iALS29_diMN18_rep1.bigwig
x bamCoverage on collection 131/iALS29_ISO_diMN18_rep1.bigwig: (Empty error message)
tar: Error exit delayed from previous errors.
```

**Comment by alexlenail** [comment]
I successfully downloaded and unzipped that collection just now. This is one of those _galaxy_ bugs. /sigh. Sometimes you just need to try the exact same thing a second time and it works.
